# token generated by AFAN in qianfan platform: https://console.bce.baidu.com/qianfan/
DEFAULT_TOKEN = '24.086e54aa50833194c18a3dd3546113b4.2592000.1724341533.282335-97980042'
# avoid to reach TPM limit: https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Llroa77io
DEFAULT_SLEEP = 5
DEFAULT_BATCH_NUM = 5